---
# tasks file for nginx

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: nginx

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: nginx

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: nginx

- name: Ensure NGINX is started and enabled on boot
  service: name={{ nginx_service_name }} state=started enabled=yes
  tags: nginx

- name: Create NGINX defaults file
  template: >
    src=nginx.defaults.j2
    dest=/etc/default/nginx
    owner=root
    group=root
    mode=0644
  notify: restart nginx
  tags: nginx
