---
# tasks file for nginx

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - nginx

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - nginx

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - nginx

- name: Create nginx defaults file
  become: yes
  template:
    src: nginx.defaults.j2
    dest: /etc/default/nginx
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  tags:
    - nginx

- name: Create nginx main configuration file
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
  tags:
    - nginx

- name: Ensure nginx is started and enabled on boot
  become: yes
  service:
    name: "{{ nginx_service_name }}"
    state: started
    enabled: yes
  tags:
    - nginx
