---
# tasks file for nginx

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: nginx

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: nginx

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: nginx

- name: Ensure NGINX is started and enabled on boot
  service: name={{ nginx_service_name }} state=started enabled=yes
  tags: nginx
