---
# tasks file for nginx (Ubuntu specific)

- name: Add nginx APT repository key
  become: yes
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  tags:
    - nginx

- name: Add nginx APT repository
  become: yes
  apt_repository:
    repo: 'deb http://nginx.org/packages/ubuntu/ trusty nginx'
    state: present
  tags:
    - nginx

- name: Install nginx packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ nginx_packages }}"
  tags:
    - nginx
