---
# handlers file for nginx

- name: restart nginx
  become: yes
  service:
    name: "{{ nginx_service_name }}"
    state: restarted
  tags:
    - nginx

- name: reload nginx
  become: yes
  service:
    name: "{{ nginx_service_name }}"
    state: reloaded
  tags:
    - nginx
